# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: clean-format
        name: clean-format
        entry: make
        args: ["clean-format"]
        language: system
        pass_filenames: false

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
        name: commitizen check
        description: >
          Check whether the current commit message follows committing rules. Allow
          empty commit messages by default, because they typically indicate to Git
          that the commit should be aborted.
        entry: cz check
        args: ["--allow-abort", "--commit-msg-file"]
        stages: [commit-msg]
        language: python
        language_version: python3
        minimum_pre_commit_version: "1.4.3"
