version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - (cd docs && make rst)

python:
  install:
  - requirements: docs/requirements_sphinx.txt
  - method: pip
    path: .

sphinx:
  configuration: docs/source/conf.py
