dataset_str: quanda-bench-test/awa2
dataset_split: train
transforms: none
wrapper:
  type: SampleTransformationDataset
  metadata:
    metadata_filename: awa2_val_shortcut.yaml
    p: 0.3
    cls_idx: 0
    seed: 42
  sample_fn: add_pink_frame
  dataset_transform: awa2_transforms
split_ref: awa2_train_shortcut
split_name: val
