dataset_str: quanda-bench-test/awa2
dataset_split: train
transforms: awa2_train_transforms
wrapper:
  type: LabelFlippingDataset
  metadata:
    metadata_filename: awa2_train_mislabeling_transform_indices.yaml
    p: 0.2
    seed: 43
split_ref: awa2_train_mislabeling
split_name: train
