dataset_str: ylecun/mnist
dataset_split: train[:1%]
transforms: "mnist_transforms"
indices: "all"
wrapper:
  type: "LabelGroupingDataset"
  metadata:
      metadata_filename: "mnist_train_unit_subclass.yaml"
      p: 1.0
      n_groups: 2
      class_to_group: "random"
      seed: 42
