dataset_str: ylecun/mnist
dataset_split: train[:1%]
transforms:
wrapper:
  type: "SampleTransformationDataset"
  metadata:
      metadata_filename: "mnist_train_unit_shortcut.yaml"
      p: 1.0
      cls_idx: 0
      seed: 42
  sample_fn: "add_white_square_mnist"
  dataset_transform: "mnist_transforms"
