model:
  pretrained_model_name: null
  module:
    name: MnistTorch
    args:
      num_outputs: 10
  trainer:
    optimizer: sgd
    optimizer_kwargs:
      weight_decay: 0.0
    criterion: cross_entropy
    criterion_kwargs: {}
    scheduler: constant
    scheduler_kwargs:
      last_epoch: -1
    lr: 0.1
    max_epochs: 15
    seed: 42
train_dataset:
  dataset_str: ylecun/mnist
  dataset_split: train
  transforms: mnist_transforms
  split_ref: mnist_train
  split_name: train
eval_dataset:
  dataset_str: ylecun/mnist
  dataset_split: test
  transforms: mnist_transforms
  filter_indices:
    split_filename: mnist_eval_mixed_main_filter.yaml
    split_name: default
val_dataset:
  dataset_str: ylecun/mnist
  dataset_split: train
  transforms: mnist_transforms
  split_ref: mnist_train
  split_name: val
logger:
  _target_: lightning.pytorch.loggers.wandb.WandbLogger
  save_dir: hydra_logs/wandb/
  project: quanda-bench
id: ad1b983-default_MixedDatasets
bench: MixedDatasets
adversarial_label: 0
bench_save_dir: bench_out
log_dir: hydra_logs
repo_id: quanda-bench-test
cache_dir: tmp
top_k: 5
model_id: '0'
correlation_fn: kendall
offline: true
seed: 42
m: 4
alpha: 0.5
subset_ids: lds_subsets.yaml
adv_dataset:
  single_class_dataset: true
  label: 0
  transforms: adversarial_transforms
  dataset_str: zalando-datasets/fashion_mnist
  split_ref: fashion_mnist
  split_name: train
cfg_output_dir: quanda/benchmarks/resources/configs
cfg_file_name: ad1b983-default_MixedDatasets.yaml
filter_by_prediction: true
ckpt: quanda-bench-test/ad1b983-default_MixedDatasets
num_checkpoints: 5
device: cuda:1
splits:
  mnist_train:
    filename: mnist_train_split.yaml
    ratios:
      train: 0.8
      val: 0.2
      test: 0.0
    seed: 42
  fashion_mnist:
    filename: fashion_mnist_split.yaml
    ratios:
      train: 0.8
      val: 0.1
      test: 0.1
    seed: 42
batch_size: 64
