model:
  module:
    name: HFGPT2
    args:
      vocab_size: 50304
      n_positions: 512
      n_ctx: 512
      n_embd: 768
      n_layer: 12
      n_head: 12
      activation_function: gelu
      tie_word_embeddings: false
fact_tracing:
  dataset_str: quanda-bench-test/trex-subset-benchmark-trex-openwebtext-ft
  dataset_split: train
  tokenizer:
    backend: tiktoken
    encoding: gpt2
  num_prompts: 20
  max_evidence_per_prompt: 5
  max_length: 64
  seed: 42
id: gpt2_trex_openwebtext_ft_TailPatch
bench: TailPatch
bench_save_dir: bench_out
repo_id: quanda-bench-test
cache_dir: tmp
device: cuda:0
use_predictions: false
batch_size: 1
k: 4
learning_rate: 1.0e-05
optimizer_kwargs: {}
tokenizer_name: gpt2
ckpt: quanda-bench-test/gpt2-small-trex-openwebtext-ft-hf
num_checkpoints: 1
meta_id: quanda-bench-test/gpt2_trex_openwebtext_ft_TailPatch_metadata
