  single_class_dataset: true
  label: 0
  transforms: "adversarial_transforms"
  dataset_str: "zalando-datasets/fashion_mnist"
  indices:
    split_filename: "fashion_mnist_split.yaml"
    split_ratios:
      train: 0.6
      val: 0.2
      test: 0.2
    seed: 42
