  single_class_dataset: true
  label: 0
  transforms: "adversarial_transforms"
  split_filename: "fashion_mnist_split.yaml"
  dataset_str: "quanda-bench-test/fashion_mnist_unit"
  save_dir: "fashion_mnist_unit"
