defaults:
  - model: bert_base_cased
  - train_dataset: qnli_train
  - eval_dataset: qnli_test
  - val_dataset: qnli_val
  - model/trainer: bert_qnli
  - logger: wandb
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: grid
  - override hydra/launcher: joblib
  - _self_

hydra:
  sweep:
    dir: "${log_dir}/${id}"
    subdir: hydra_logs

  launcher:
    n_jobs: 3

  sweeper:
    direction:
      - maximize
    study_name: "${cfg_file_name}"
    storage: null
    n_trials: 20
    n_jobs: 3
    params:
      model.trainer.max_epochs: choice(20, 30)

id: "bert_qnli"
bench: LDS
bench_save_dir: "bench_out"
log_dir: hydra_logs
repo_id: "quanda-bench-test"
cache_dir: "tmp"
top_k: 5
model_id: "0"
correlation_fn: "kendall"
offline: true
seed: 42
device: "auto"
use_predictions: true

m: 30
alpha: 0.5

subset_ids: lds_subsets.yaml

ckpts:
  - "${repo_id}/${id}"
meta_id: "${repo_id}/${id}_metadata"
