defaults:
  - model: cifar_resnet9_base
  - train_dataset: cifar10_train_unit
  - eval_dataset: cifar10_test_unit
  - val_dataset: cifar10_val
  - model/trainer: default
  - logger: wandb
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: grid
  - override hydra/launcher: joblib
  - _self_

hydra:
  sweep:
    dir: "${log_dir}/${id}"
    subdir: hydra_logs

  launcher:
    n_jobs: 10

  sweeper:
    direction:
      - maximize
    study_name: "${cfg_file_name}"
    storage: null
    n_trials: 20
    n_jobs: 10
    params:
      model.trainer.lr: choice(0.1, 0.2, 0.4)
      model.trainer.optimizer: choice("sgd")
      model.trainer.max_epochs: choice(12, 24, 36)

id: "default"
bench: ClassDetection
adversarial_label: 0
bench_save_dir: "bench_out"
log_dir: hydra_logs
repo_id: "quanda-bench-test"
cache_dir: "tmp"
top_k: 5
model_id: "0"
correlation_fn: "kendall"
offline: true
seed: 42
device: "cuda:0"
batch_size: 64

m: 100
alpha: 0.5

subset_ids: lds_subsets.yaml

ckpt: "${repo_id}/${id}"
num_checkpoints: 5
meta_id: "${repo_id}/${id}_metadata"

splits:
  cifar10_train:
    filename: cifar10_train_split.yaml
    ratios: {train: 0.8, val: 0.2, test: 0.0}
    seed: 42
  cifar10_train_subclass:
    filename: cifar10_train_subclass_split.yaml
    ratios: {train: 0.8, val: 0.2, test: 0.0}
    seed: 42
  cifar10_train_shortcut:
    filename: cifar10_train_shortcut_split.yaml
    ratios: {train: 0.8, val: 0.2, test: 0.0}
    seed: 42
  cifar10_train_mislabeling:
    filename: cifar10_train_mislabeling_split.yaml
    ratios: {train: 0.8, val: 0.2, test: 0.0}
    seed: 42
  svhn:
    filename: svhn_split.yaml
    ratios: {train: 0.16, val: 0.02, test: 0.02}
    seed: 42