name: dattri_if_cg
cls: quanda.explainers.wrappers.DattriIFCG
kwargs:
  loss_func:
    _target_: hydra.utils.get_method
    path: quanda.explainers.wrappers.dattri_losses.causal_lm_batched_loss
  task: causal_lm
  hf_input_keys: [input_ids, attention_mask]
  max_iter: 100
  tol: 1.0e-07
  regularization: 0.01
  batch_size: 1
