name: dattri_ekfac
cls: quanda.explainers.wrappers.DattriEKFAC
kwargs:
  loss_func:
    _target_: hydra.utils.get_method
    path: quanda.explainers.wrappers.dattri_losses.bert_classification_batched_loss
  damping: 0.0
  batch_size: ${batch_size}
