name: kronfluence
cls: quanda.explainers.wrappers.Kronfluence
kwargs:
  task_module:
    _target_: quanda.explainers.wrappers.kronfluence_tasks.TextClassificationTask
    tracked_modules: [classifier]
  batch_size: 8
  device: ${device}
