defaults:
  - model: mnist_lenet_base
  - train_dataset: mnist_train_unit
  - adv_dataset: fashion_mnist_unit
  - _self_

adversarial_label: 0
adv_split_path: tests/assets/fashion_mnist_split.pth
experiment_name: default_experiment
seed: 42 