defaults:
  - explainer: similarity
  - override hydra/launcher: joblib
  - override hydra/sweeper: basic
  - _self_

hydra:
  sweep:
    dir: "${results_dir}/${bench}__${explainer.name}"
    subdir: ${hydra.job.num}
  launcher:
    n_jobs: 1

bench: cifar_class_detection
cache_dir: ./eval_bench/cifar
results_dir: ./eval_results
device: cuda:0
batch_size: 32

max_eval_n: 1000
eval_seed: 42

final_fc_layer: model.9
