defaults:
  - explainer: similarity
  - override hydra/launcher: joblib
  - override hydra/sweeper: basic
  - _self_

hydra:
  sweep:
    dir: "${results_dir}/${bench}__${explainer.name}"
    subdir: ${hydra.job.num}
  launcher:
    n_jobs: 1

bench: mnist_class_detection
root_dir: ${cluster_or_local:/data/cluster/users/bareeva/quanda_output_new,/data2/bareeva/Projects/quanda/cluster_output_new}
cache_dir: ${root_dir}/eval_bench/mnist
results_dir: ${root_dir}/eval_results/mnist

#cache_dir: ./eval_bench/mnist
#results_dir: ./eval_results/mnist
device: cpu
batch_size: 32

bench_eval:
  mnist_class_detection: {max_eval_n: 1000, eval_seed: 42}
  mnist_subclass_detection: {max_eval_n: 1000, eval_seed: 42}
  mnist_mislabeling_detection: {max_eval_n: null, eval_seed: 42}
  mnist_shortcut_detection: {max_eval_n: 1000, eval_seed: 42}
  mnist_mixed_datasets: {max_eval_n: 1000, eval_seed: 42}
  mnist_linear_datamodeling: {max_eval_n: 1000, eval_seed: 42}
  mnist_top_k_cardinality: {max_eval_n: 1000, eval_seed: 42}
  mnist_model_randomization: {max_eval_n: 1000, eval_seed: 42}

final_fc_layer: fc_3