defaults:
  - explainer: similarity
  - override hydra/launcher: joblib
  - override hydra/sweeper: basic
  - _self_

hydra:
  sweep:
    dir: "${results_dir}/${bench}__${explainer.name}"
    subdir: ${hydra.job.num}
  launcher:
    n_jobs: 1

bench: mnist_class_detection
cache_dir: ./tmp_bench
results_dir: ./eval_results
device: cpu
batch_size: 32
