name: Lint

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: "3.11"
      - name: Install tox-gh
        run: pip install tox-gh
      - name: Run flake8
        run: tox run -e lint
      - name: Run mypy
        run: tox run -e type