name: release

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  cd:
    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: pip install semantic-release

      - name: Use Python Semantic Release to prepare release
        id: release
        uses: python-semantic-release/python-semantic-release@v8.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version in __init__.py
        if: steps.release.outputs.released == 'true'
        run: |
          VERSION=$(python -c "import semantic_release; print(semantic_release.get_current_version())")
          sed -i "s/__version__ = .*/__version__ = \"$VERSION\"/" quanda/__init__.py

      - name: Commit version bump
        if: steps.release.outputs.released == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add quanda/__init__.py
          git commit -m "chore: bump version to $VERSION"
          git push origin main

      - name: Publish package distributions to GitHub Releases
        if: steps.release.outputs.released == 'true'
        uses: python-semantic-release/upload-to-gh-release@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true