name: release

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  cd:
    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Python Semantic Release to prepare release
        id: release
        uses: python-semantic-release/python-semantic-release@v8.3.0
        with:
          github_token: ${{ secrets.QUANDA_ADMIN }}
          changelog: true
          tag: true

      - name: Push changes to a new branch and create a PR
        run: |
          # Create a new branch from main
          git checkout -b version-bump-${{ steps.release.outputs.version }}

          # Push changes to the new branch
          git push origin version-bump-${{ steps.release.outputs.version }}

          # Create a pull request using GitHub CLI (gh)
          gh pr create --base main --head version-bump-${{ steps.release.outputs.version }} --title "chore: Version bump to ${{ steps.release.outputs.version }}" --body "Automated version bump"

        env:
          GITHUB_TOKEN: ${{ secrets.QUANDA_ADMIN }} 

